nodejs_version: "8.x"
rabbitmq_server_url: "amqp://{{ rabbitmq_server_user}}:{{ rabbitmq_server_pass}}@{{ rabbitmq_server_host }}{{ rabbitmq_server_vpath }}"

package_name: onlyoffice-documentserver-ie

psql: "PGPASSWORD={{ db_server_pass }} psql -q -h{{ db_server_host }} -U{{ db_server_user }} -w -d{{ db_server_name }}"
createdb_sql: /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql
cluster_mode: true
