---
  - name: Add onlyoffice gpg keys
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: "CB2DE8E5"
      state: present
    become: yes

  - name: Add onlyoffice repositories
    apt_repository:
      repo: "{{ package_repo }}"
      state: present
    become: yes

  - name: Get documentserver dependency list
    shell: "apt-cache depends {{ package_name }} | grep \"Depends\" | cut -f2 -d \":\" | cut -c 2- | sed \"/<.*>/d\" | sed \"/nginx.*/d\""
    register: ds_dep
    become: yes

  - name: Install documentserver dependency
    apt:
      name: "{{ item }}"
    with_items: "{{ ds_dep.stdout_lines }}"
    become: yes
