---
- hosts: database

  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.postgresql, become: yes }
    - { role: ds-createdb, become: yes }

- hosts: filestorage

  pre_tasks:
  - name: Setup exported path right
    file:
      path: "{{ item.strip().split()[0] }}"
      state: directory
      owner: nobody
      group: nogroup
    with_items: "{{ nfs_exports }}"
    become: yes

  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.nfs, become: yes }
    - { role: documentserver-fonts, become: yes }

- hosts: rabbitmq
  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: Stouts.rabbitmq, become: yes }

- hosts: redis
  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.redis, become: yes }

- hosts: documentservers
  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.nodejs, become: yes }
    - { role: documentserver, become: yes }

- hosts: loadbalancer
  pre_tasks:
  - name: Copy certificate
    copy: src="{{ ssl_certificate }}" dest="{{ loadbalancer_ssl_certificate  }}"
    when: "{{ loadbalancer_ssl }}"
    become: yes

  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.haproxy, become: yes }

- hosts: documentserver-example
  roles:
    - { role: geerlingguy.ntp, become: yes }
    - { role: kamaln7.swapfile, become: yes }
    - { role: geerlingguy.nodejs, become: yes }
    - { role: documentserver-example, become: yes }
