---
- name: configure /etc/hosts
  hosts: all-postgresql
  become: yes
  tasks:
  - name: Update /etc/hosts
    blockinfile:
      path: /etc/hosts
      create: yes
      block: |
        {% for host in groups['zookeeper'] %}
        {{ hostvars[host].ansible_default_ipv4.address }}  {{ hostvars[host].ansible_fqdn }}  {{ hostvars[host].ansible_hostname }}
        {% endfor  %}

- name: configure zookeeper
  hosts: zookeeper
  roles:
    - { role: andrewrothstein.zookeeper-cluster, become: yes }

- name: install packages
  hosts: database
  become: yes
  tasks:
  - name: install packages centos-release-scl
    yum: name=centos-release-scl state=latest
    when: ansible_os_family == 'RedHat'

- name: install postgresql-servers
  hosts: database
  roles:
    - { role: kostiantyn-nemchenko.patroni, become: yes }

- name: configure haproxy selinux
  hosts: haproxy_postgresql
  tasks:
  - name: configuring selinux
    command: setsebool -P haproxy_connect_any=1
    when: ansible_os_family == 'RedHat'
  become: yes

- name: configure haproxy server
  hosts: haproxy_postgresql
  roles:
    - { role: wftech.haproxy, become: yes }
