---
- hosts: database

  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.postgresql

- hosts: filestorage

  pre_tasks:
  - name: Setup exported path right
    file:
      path: "{{ item.strip().split()[0] }}"
      state: directory
      owner: nobody
      group: nogroup
    with_items: "{{ nfs_exports }}"

  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.nfs

- hosts: rabbitmq
  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - Stouts.rabbitmq

- hosts: redis
  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.redis

- hosts: documentservers
  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.nodejs
    - documentserver

- hosts: loadbalancer
  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.haproxy

- hosts: documentserver-example
  roles:
    - geerlingguy.ntp
    - kamaln7.swapfile
    - geerlingguy.nodejs
    - Stouts.supervisor
    - documentserver-example
