---
- name: configure the master redis server
  hosts: redis-master
  roles:
    - { role: davidwittman.redis, become: yes }

- name: configure redis slaves
  hosts: redis-slave
  roles:
    - { role: davidwittman.redis, become: yes }

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  vars:
    - redis_sentinel_monitors:
      - name: master01
        host: "{{ groups['redis-master'][0] }}"
        port: 6379
    - redis_sentinel: True
  roles:
    - { role: davidwittman.redis, become: yes }

- name: configure haproxy selinux
  hosts: haproxy_redis
  tasks:
  - name: configuring selinux
    command: setsebool -P haproxy_connect_any=1
    when: ansible_os_family == 'RedHat'
  become: yes

- name: configure haproxy server
  hosts: haproxy_redis
  roles:
    - { role: wftech.haproxy, become: yes }
