---
- name: configure the master redis server
  hosts: redis-master
  roles:
    - { role: davidwittman.redis, become: yes }

- name: configure redis slaves
  hosts: redis-slave
  roles:
    - { role: davidwittman.redis, become: yes }

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  vars:
    - redis_sentinel_monitors:
      - name: master01
        host: "{{ groups['redis-master'][0] }}"
        port: 6379
    - redis_sentinel: True
  roles:
    - { role: davidwittman.redis, become: yes }
