---
- name: configure /etc/hosts
  hosts: all-rabbitmq
  become: yes
  tasks:
  - name: Update /etc/hosts
    blockinfile:
      path: /etc/hosts
      create: yes
      block: |
        {% for host in groups['rabbitmq'] %}
        {{ hostvars[host].ansible_default_ipv4.address }}  {{ hostvars[host].ansible_fqdn }}  {{ hostvars[host].ansible_hostname }}
        {% endfor  %}

- name: install apt-transport-https
  hosts: rabbitmq
  tasks:
  - name: install apt-transport-https
    apt: name=apt-transport-https state=latest
    when: ansible_os_family == 'Debian'
  become: yes

- name: configure rabbitmq-master
  hosts: rabbitmq-master
  roles:
    - { role: rockandska.erlang, become: yes }
    - { role: rockandska.rabbitmq, become: yes }

- name: configure rabbitmq-slave
  hosts: rabbitmq-slave
  roles:
    - { role: rockandska.erlang, become: yes }
    - { role: rockandska.rabbitmq, become: yes }

- name: configure cluster policies
  hosts: rabbitmq-master
  tasks:
  - name: configuring policies
    command: rabbitmqctl set_policy ha-amq ".*" '{"ha-mode":"all","ha-sync-mode":"automatic","ha-promote-on-failure":"when-synced","queue-master-locator":"min-masters"}'
  become: yes
