- src: geerlingguy.ntp

- src: https://github.com/DavidWittman/ansible-redis
  name: davidwittman.redis
  
- src: wftech.haproxy

- src: https://github.com/agolybev/ansible-role-postgresql
  name: geerlingguy.postgresql

- src: https://github.com/agolybev/ansible-role-haproxy.git
  name: geerlingguy.haproxy

- src: geerlingguy.nodejs

- src: geerlingguy.nfs

- src: Stouts.rabbitmq

- src: kamaln7.swapfile
