- src: geerlingguy.ntp

- src: geerlingguy.redis

# - src: https://github.com/agolybev/ansible-role-postgresql
#   name: geerlingguy.postgresql

- src: https://github.com/andrewrothstein/ansible-zookeeper
  name: andrewrothstein.zookeeper

- src: https://github.com/ONLYOFFICE/ansible-zookeeper-cluster
  name: andrewrothstein.zookeeper-cluster

- src: kostiantyn-nemchenko.patroni

- src: wftech.haproxy

- src: https://github.com/agolybev/ansible-role-haproxy.git
  name: geerlingguy.haproxy

- src: geerlingguy.nodejs

- src: geerlingguy.nfs

- src: Stouts.rabbitmq

- src: kamaln7.swapfile
