---
collections:
  - name: community.general

  - name: ansible.posix

  - name: community.rabbitmq

roles:
  - src: geerlingguy.ntp

  - src: https://github.com/DavidWittman/ansible-redis
    name: davidwittman.redis

  - src: wftech.haproxy

  - src: andrewrothstein.bash

  - src: andrewrothstein.temurin

  - src: andrewrothstein.unarchivedeps

  - src: andrewrothstein.unarchive-deps

  - src: andrewrothstein.zookeeper

  - src: andrewrothstein.zookeeper-cluster

  - src: https://github.com/kostiantyn-nemchenko/ansible-role-patroni.git
    name: kostiantyn-nemchenko.patroni

  - src: geerlingguy.nodejs

  - src: geerlingguy.nfs

  - src: rockandska.erlang

  - src: rockandska.rabbitmq

  - src: geerlingguy.swap

  - src: https://github.com/ONLYOFFICE/ansible-role-documentserver.git
    name: onlyoffice.documentserver

  - src: ome.nfs_mount
