- src: geerlingguy.ntp

- src: https://github.com/DavidWittman/ansible-redis
  name: davidwittman.redis
  
- src: wftech.haproxy

- src: andrewrothstein.zookeeper

- src: andrewrothstein.zookeeper-cluster

- src: kostiantyn-nemchenko.patroni

- src: geerlingguy.nodejs

- src: geerlingguy.nfs

- src: rockandska.erlang

- src: rockandska.rabbitmq

- src: geerlingguy.swap

- src: https://github.com/ONLYOFFICE/ansible-role-documentserver.git
  name: onlyoffice.documentserver

- src: ome.nfs_mount

- src: https://github.com/ONLYOFFICE/document-server-cluster/roles/onlyoffice_gdnsd.git
  name: onlyoffice_gdnsd
