- src: geerlingguy.ntp

- src: geerlingguy.redis

- src: https://github.com/agolybev/ansible-role-postgresql
  name: geerlingguy.postgresql

- src: geerlingguy.haproxy

- src: geerlingguy.nodejs

- src: geerlingguy.nfs

- src: Stouts.rabbitmq

