onlyoffice_repo_file: "onlyoffice"
package_name: onlyoffice-documentserver-integration
package_repo: "deb http://download.onlyoffice.com/repo/debian squeeze main"

onlyoffice_default_config: /etc/onlyoffice/documentserver/default.json
json: json -q -f {{ onlyoffice_default_config }}

