---
#  - name: Add ubuntu gpg keys
#    apt_key: keyserver={{ item.server }} id={{ item.key }} state=present
#    with_items:
#      - { server: 'keyserver.ubuntu.com', key: 'BA9EF27F', vendor: 'ubuntu' }
#    sudo: yes
 
  - name: Add onlyoffice gpg keys
    apt_key:
      url: "http://download.onlyoffice.com/repo/onlyoffice.key"
      state: present
    sudo: yes

# - name: Add repositories		
#   apt_repository: repo="{{ item }}" state=present		
#   with_items:		
#     - "deb http://archive.ubuntu.com/ubuntu precise main universe multiverse"		
#   sudo: yes

  - name: Add onlyoffice repositories
    apt_repository:
      repo: {{ package_repo }}
      state: present
      filename: {{ onlyoffice_repo_file }}
    sudo: yes
  
  - name: Say 'yes' to ttf-mscorefonts-installer
    shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    sudo: yes
    
  - name: Accept license
    shell: echo {{ package_name }} onlyoffice/accepted-onlyoffice-license select true | debconf-set-selections
    sudo: yes
    
  - name: Install packages
    apt: name={{ item.name }} update_cache=yes force=yes state={{ item.state }}
    with_items:
      - { name: software-properties-common, state: present }
      - { name: {{ package_name }}, state: latest }
    sudo: yes
