---
  - name: Add onlyoffice gpg keys
    apt_key:
      keyserver: "keyserver.ubuntu.com"
      id: "CB2DE8E5"
      state: present
    become: yes

  - name: Add onlyoffice repositories
    apt_repository:
      repo: "{{ package_repo }}"
      state: present
    sudo: yes
  
  - name: Say 'yes' to ttf-mscorefonts-installer
    shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    become: yes
    
  - name: Accept license
    shell: echo {{ package_name }} onlyoffice/accepted-onlyoffice-license select true | debconf-set-selections
    become: yes
    
  - name: Set up db host name
    shell: echo {{ package_name }} onlyoffice/db-host select {{ db_server_host }} | debconf-set-selections
    when: db_server_host != ""
    become: yes

  - name: Set up db name
    shell: echo {{ package_name }} onlyoffice/db-name select {{ db_server_name }} | debconf-set-selections
    when: db_server_name != ""

  - name: Set up db user
    shell: echo {{ package_name }} onlyoffice/db-user select {{ db_server_user }} | debconf-set-selections
    when: db_server_user != ""
    become: yes

  - name: Set up db user password
    shell: echo {{ package_name }} onlyoffice/db-pwd select {{ db_server_pass }} | debconf-set-selections
    when: db_server_pass != ""
    become: yes

  - name: Unmount existed filestorage
    mount:
      name: "{{ filestorage_mount_path }}"
      src: "{{ filestorage_host }}:{{ filestorage_path }}"
      fstype: "{{ filestorage_fs }}"
      state: unmounted
    when: (filestorage_host != "") and (filestorage_path != "") and (filestorage_fs != "")
    become: yes
    ignore_errors: yes

  - name: Install packages
    apt: name={{ item.name }} update_cache=yes force=yes state={{ item.state }}
    with_items:
      - { name: nfs-common, state: latest }
      - { name: "{{ package_name }}", state: latest }
    become: yes

  - name: Set up redis host name
    shell: "{{ json }} -I -e 'this.services.CoAuthoring.redis.host  = \"{{ redis_server_host }}\"'"
    when: redis_server_host != ""

  - name: Set up redis port number
    shell: "{{ json }} -I -e 'this.services.CoAuthoring.redis.port  = \"{{ redis_server_port }}\"'"
    when: redis_server_port != ""

  - name: Set up rabbitmq url
    shell: "{{ json }} -I -e 'this.rabbitmq.url = \"{{ rabbitmq_server_url }}\"'"
    when: rabbitmq_server_url != ""

  - name:  Mount filestorage
    mount:
      name: "{{ filestorage_mount_path }}"
      src: "{{ filestorage_host }}:{{ filestorage_path }}"
      fstype: "{{ filestorage_fs }}"
      state: mounted
      opts: rw
    when: (filestorage_host != "") and (filestorage_path != "") and (filestorage_fs != "")
    become: yes

  - name: Restart documentserver
    supervisorctl:
      name: "{{ item }}"
      state: restarted
    with_items:
    - 'onlyoffice-documentserver:converter'
    - 'onlyoffice-documentserver:docservice'
    become: yes
